server:
  port: 8081
spring:
  application:
    name: address
  datasource:
    url: jdbc:postgresql://dpg-d1efnjje5dus73bcc9o0-a.oregon-postgres.render.com:5432/ppdb
    username: ppdb_em5e_user
    password: F9dlSTHjOA3DQpSiPTyGafx0aPmFJ6ck
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
