server:
  port: 8082
spring:
  application:
    name: address
  datasource:
    url: jdbc:postgresql://dpg-d1efnjje5dus73bcc9o0-a.oregon-postgres.render.com:5432/ppdb
    username: ppdb_em5e_user
    password: F9dlSTHjOA3DQpSiPTyGafx0aPmFJ6ck
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob.non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
